### ISSUE TITLE
用户和角色的多态关联没有找到auth.guards的配置

### ISSUE THREAD

**Issue by pwjbj** [donjan-deng/la-user-center#1]
function getModelForGuard(string $guard)
    {
        return collect(config('auth.guards'))
            ->map(function ($guard) {
                if (! isset($guard['provider'])) {
                    return;
                }

                return config("auth.providers.{$guard['provider']}.model");
            })->get($guard);
    }

**Comment by donjan-deng** [comment]
更新hyperf-permission至新版或者1.0.4

**Comment by pwjbj** [comment]
config('permission.models.user');  这个好像没有配置

**Comment by donjan-deng** [comment]
<https://github.com/donjan-deng/hyperf-permission/blob/master/publish/permission.php>照着改配置
